using Photon.Pun;
using System.Collections.Generic;
using UnityEngine;

//Script attached to object in scene that represents a card pile.
//The order of the card pile is randomised the same for each client by using the same seed.
//This seed is generated by the master client. 
//Any card taken from the pile is put at the bottom like in real monopoly. 
//Once order of cards is randomised at the start, there is no need to sync the queue across clients as UI on each client grabs a card each simultaneuosly.

public class CardPile : MonoBehaviourPun
{
    [SerializeField] private CardCollection myCardCollection;
    private Queue<CardData> cardQueue;

    private void Start()
    {
        if(PhotonNetwork.IsMasterClient)
        {
            System.Random rng = new System.Random();
            int seed = rng.Next(0, 100);
            photonView.RPC(nameof(InitialiseCardQueue), RpcTarget.All, seed);
        }
    }

    [PunRPC]
    private void InitialiseCardQueue(int seed)
    {
        List<CardData> cardDataList = new List<CardData>(myCardCollection.cardDataList);
        Shuffle(cardDataList, seed);
        cardQueue = new Queue<CardData>(cardDataList);
    }

    public CardData GrabCard()
    {
        CardData card = cardQueue.Dequeue();
        cardQueue.Enqueue(card);
        return card;
    }

    public static void Shuffle<T>(IList<T> list, int seed)
    {
        var rng = new System.Random(seed);
        int n = list.Count;

        while (n > 1)
        {
            n--;
            int k = rng.Next(n + 1);
            T value = list[k];
            list[k] = list[n];
            list[n] = value;
        }
    }
}